name: Update WebProxy

on:
  push:
    paths:
      - 'WebProxy.js'
  pull_request:
    paths:
      - 'WebProxy.js'
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          check-latest: true

      - name: Make .env file
        run: |
          echo "token=${{ secrets.TOKEN }}" >> .env
          echo "accountId=${{ secrets.ACCOUNT_ID }}" >> .env

      - name: Install npm packages
        run: npm install

      - name: Run prettier
        run: npm run prettier

      - name: Run update script
        run: npm run update
